CREATE TABLE "swap_intents" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"kind" text DEFAULT 'swap' NOT NULL,
	"side" text,
	"input_mint" text NOT NULL,
	"output_mint" text NOT NULL,
	"in_amount_raw" numeric(40, 0) NOT NULL,
	"expected_out_raw" numeric(40, 0),
	"min_out_raw" numeric(40, 0),
	"fee_bps" integer DEFAULT 0 NOT NULL,
	"fee_usdc_micro" bigint DEFAULT 0 NOT NULL,
	"slippage_bps" integer,
	"price_impact_bps" integer,
	"provider" text,
	"route_label" text,
	"destination_address" text,
	"message_hash" text NOT NULL,
	"last_valid_block_height" bigint NOT NULL,
	"status" text DEFAULT 'built' NOT NULL,
	"signature" text,
	"error_code" text,
	"error_detail" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"submitted_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	CONSTRAINT "swap_intents_signature_unique" UNIQUE("signature"),
	CONSTRAINT "swap_intents_kind_check" CHECK ("swap_intents"."kind" in ('swap', 'withdraw', 'gas_topup')),
	CONSTRAINT "swap_intents_side_check" CHECK ("swap_intents"."side" in ('buy', 'sell')),
	CONSTRAINT "swap_intents_status_check" CHECK ("swap_intents"."status" in ('built', 'submitted', 'confirmed', 'failed', 'expired')),
	CONSTRAINT "swap_intents_provider_check" CHECK ("swap_intents"."provider" in ('jupiter', 'titan', 'internal')),
	CONSTRAINT "swap_intents_in_amount_check" CHECK ("swap_intents"."in_amount_raw" > 0),
	CONSTRAINT "swap_intents_min_out_check" CHECK ("swap_intents"."min_out_raw" >= 0 and "swap_intents"."min_out_raw" <= "swap_intents"."expected_out_raw"),
	CONSTRAINT "swap_intents_fee_check" CHECK ("swap_intents"."fee_bps" >= 0 and "swap_intents"."fee_usdc_micro" >= 0),
	CONSTRAINT "swap_intents_message_hash_check" CHECK ("swap_intents"."message_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "swap_intents_swap_fields_check" CHECK ("swap_intents"."kind" <> 'swap' or ("swap_intents"."side" is not null and "swap_intents"."expected_out_raw" is not null and "swap_intents"."min_out_raw" is not null and "swap_intents"."provider" is not null))
);
--> statement-breakpoint
ALTER TABLE "swap_intents" ADD CONSTRAINT "swap_intents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "swap_intents_user_time_idx" ON "swap_intents" USING btree ("user_id","created_at" DESC NULLS LAST);