/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check that the API and its database are up
         * @description Answers 503 when the database doesn't respond within 2 seconds.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The API and the database are up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is down or too slow. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your account
         * @description The first call creates your account: it reads your Solana wallet from your sign-in and gives you a random username. Later calls return the same account.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Your account. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description `UNAUTHORIZED`: the access token is missing, expired or not valid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description `WALLET_NOT_READY`: your wallet is still being created right after sign-in. Try again in a moment. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change your username
         * @description Choosing a name, or keeping the random one, counts as a change: the next one is allowed 30 days later. Sending the name you already chose changes nothing.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MeUpdate"];
                };
            };
            responses: {
                /** @description Your account, with the new name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description `VALIDATION_FAILED`: the name breaks the format. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description `UNAUTHORIZED`: the access token is missing, expired or not valid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description `USERNAME_TAKEN`: someone has the name. `USERNAME_RESERVED`: the name is blocked, or too close to a blocked name. `WALLET_NOT_READY`: see GET /v1/me. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description `USERNAME_CHANGE_TOO_SOON`: you changed it less than 30 days ago. `usernameChangeableAt` on GET /v1/me says when you can change it again. */
                429: {
                    headers: {
                        /** @description Seconds until you can change your username again. */
                        "Retry-After": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/me/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your balances
         * @description USDC and SOL in your wallet, read from Solana at the `confirmed` level. The answer can be up to 5 seconds old. More tokens will be listed as they're added.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Your balances. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Balances"];
                    };
                };
                /** @description `UNAUTHORIZED`: the access token is missing, expired or not valid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description `WALLET_NOT_READY`: see GET /v1/me. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usernames/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest a username
         * @description A random `adjective_animal_NN` name that nobody has. No sign-in needed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A free name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsernameSuggestion"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usernames/{name}/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check whether a username is free
         * @description Usernames are 3–20 characters: a–z, 0–9 and _, starting with a letter. Case doesn't matter. No sign-in needed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Whether the name is free. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsernameAvailability"];
                    };
                };
                /** @description `VALIDATION_FAILED`: the name is longer than 64 characters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable, machine-readable code. Handle codes you don't know as a generic error.
                 * @example NOT_FOUND
                 */
                code: string;
                /**
                 * @description A sentence you can show to the user.
                 * @example We couldn't find that.
                 */
                message: string;
                /**
                 * @description The same id as the x-request-id header. Quote it when you report a problem.
                 * @example 0192b6f0-7c1e-7a3b-9d7e-3f5c1a2b4d6e
                 */
                requestId: string;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "error";
            checks: {
                /** @enum {string} */
                database: "ok" | "down";
            };
        };
        Me: {
            /**
             * Format: uuid
             * @description Your account id.
             * @example 0192b6f0-7c1e-7a3b-9d7e-3f5c1a2b4d6e
             */
            id: string;
            /**
             * @description Your public name. New accounts get a random one, such as calm_otter_42.
             * @example calm_otter_42
             */
            username: string;
            /**
             * @description False until you choose a name or keep the random one, for example during onboarding.
             * @example false
             */
            usernameChosen: boolean;
            /**
             * Format: date-time
             * @description When you can change your username again (once every 30 days), or null if you can change it now.
             * @example null
             */
            usernameChangeableAt: string | null;
            /** @description Your Solana wallet address, where you add funds. It comes from your sign-in on the server, never from the request. */
            walletAddress: string;
            /**
             * Format: date-time
             * @description When the account was created.
             * @example 2026-09-26T10:00:00.000Z
             */
            createdAt: string;
        };
        MeUpdate: {
            /**
             * @description Your new username: 3–20 characters, a–z, 0–9 and _, starting with a letter. It's saved in lowercase. Send your current name to keep it.
             * @example maya
             */
            username: string;
        };
        Balances: {
            balances: components["schemas"]["Balance"][];
            /**
             * Format: date-time
             * @description When these amounts were read from Solana.
             * @example 2026-09-26T10:00:00.000Z
             */
            updatedAt: string;
        };
        Balance: {
            token: components["schemas"]["Token"];
            /**
             * @description In the token's smallest unit, as a string so no digit is lost: 50 USDC is "50000000".
             * @example 50000000
             */
            amountRaw: string;
        };
        Token: {
            /** @example EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v */
            mint: string;
            /** @example USDC */
            symbol: string;
            /**
             * @description How many of the raw amount's digits come after the decimal point.
             * @example 6
             */
            decimals: number;
        };
        UsernameSuggestion: {
            /**
             * @description A random name that nobody has right now.
             * @example calm_otter_42
             */
            username: string;
        };
        UsernameAvailability: {
            /**
             * @description The name as it would be saved: in lowercase.
             * @example maya
             */
            username: string;
            available: boolean;
            /**
             * @description Why the name isn't available: `taken` (someone has it, maybe you), `reserved` (blocked, or too close to a blocked name) or `invalid` (breaks the format). Treat any other value as not available.
             * @example taken
             */
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
