/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check that the API and its database are up
         * @description Answers 503 when the database doesn't respond within 2 seconds.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The API and the database are up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is down or too slow. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable, machine-readable code. Handle codes you don't know as a generic error.
                 * @example NOT_FOUND
                 */
                code: string;
                /**
                 * @description A sentence you can show to the user.
                 * @example We couldn't find that.
                 */
                message: string;
                /**
                 * @description The same id as the x-request-id header. Quote it when you report a problem.
                 * @example 0192b6f0-7c1e-7a3b-9d7e-3f5c1a2b4d6e
                 */
                requestId: string;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "error";
            checks: {
                /** @enum {string} */
                database: "ok" | "down";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
